// <auto-generated />
using System;
using FootballBooking.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FootballBooking.Migrations
{
    [DbContext(typeof(FootballBookingDbContext))]
    [Migration("20221215162441_Init_db")]
    partial class Init_db
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FootballBooking.Entities.Model.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BookerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("StadiumId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookerId")
                        .IsUnique()
                        .HasFilter("[BookerId] IS NOT NULL");

                    b.HasIndex("StadiumId")
                        .IsUnique()
                        .HasFilter("[StadiumId] IS NOT NULL");

                    b.ToTable("Address", (string)null);
                });

            modelBuilder.Entity("FootballBooking.Entities.Model.Booker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Booker", (string)null);
                });

            modelBuilder.Entity("FootballBooking.Entities.Model.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BookTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("BookerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StadiumId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BookerId");

                    b.HasIndex("StadiumId");

                    b.ToTable("Booking", (string)null);
                });

            modelBuilder.Entity("FootballBooking.Entities.Model.Stadium", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<Guid>("StadiumOwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("StadiumStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StadiumOwnerId");

                    b.ToTable("Stadium", (string)null);
                });

            modelBuilder.Entity("FootballBooking.Entities.Model.StadiumOwner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StadiumOwner", (string)null);
                });

            modelBuilder.Entity("FootballBooking.Entities.Model.Address", b =>
                {
                    b.HasOne("FootballBooking.Entities.Model.Booker", "Booker")
                        .WithOne("Address")
                        .HasForeignKey("FootballBooking.Entities.Model.Address", "BookerId");

                    b.HasOne("FootballBooking.Entities.Model.Stadium", "Stadium")
                        .WithOne("Address")
                        .HasForeignKey("FootballBooking.Entities.Model.Address", "StadiumId");

                    b.Navigation("Booker");

                    b.Navigation("Stadium");
                });

            modelBuilder.Entity("FootballBooking.Entities.Model.Booking", b =>
                {
                    b.HasOne("FootballBooking.Entities.Model.Booker", "Booker")
                        .WithMany("Bookings")
                        .HasForeignKey("BookerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootballBooking.Entities.Model.Stadium", "Stadium")
                        .WithMany("Bookings")
                        .HasForeignKey("StadiumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booker");

                    b.Navigation("Stadium");
                });

            modelBuilder.Entity("FootballBooking.Entities.Model.Stadium", b =>
                {
                    b.HasOne("FootballBooking.Entities.Model.StadiumOwner", "StadiumOwner")
                        .WithMany("Stadiums")
                        .HasForeignKey("StadiumOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StadiumOwner");
                });

            modelBuilder.Entity("FootballBooking.Entities.Model.Booker", b =>
                {
                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("FootballBooking.Entities.Model.Stadium", b =>
                {
                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("FootballBooking.Entities.Model.StadiumOwner", b =>
                {
                    b.Navigation("Stadiums");
                });
#pragma warning restore 612, 618
        }
    }
}
